### PR TITLE
Add documentation for the valueSeparator

### PR DESCRIPTION
**Pull request by drapergeek**

### CODE REVIEW

**Comment by iStefo** [comment]
Thanks! I'm still wondering in which use case one would actually want to use the value separator. And whether it wouldn't be a good thing to have it turned of as an default...

**Comment by drapergeek** [comment]
I agree that by default I'd prefer to have it turned off. It was definitely an unexpected side effect that took me a bit to track down.

The only reason I didn't remove it as a default was to allow you to drop a new version without a 2.0 release. I'm definitely in favor of deprecating it and then in 2.0 removing the default.

**Comment by drapergeek** [comment]
Btw, any idea when you'll drop a new release? I need to use this so I'm trying to avoid publishing my own version while waiting :smile:

**Comment by iStefo** [comment]
Do you know what is the best way to deprecate the default behaviour? I mean, we can't detect if any people already rely on it. Checking if a value string contains a comma seems rather expensive, right?

I will go through the open pull requests and really soon release the 1.3.0 version.

**Comment by drapergeek** [comment]
I would say that anyone who doesn't provide the `valueSeparator` option would get a depreciation notice in their console explaining the current behavior and if they want to continue using the current behavior they need to specify `valueSeparator=','`. If they are using the `skipValueSeparator` you print out a similar deprecation that it won't be required in the next version, though it wouldn't hurt if they left it in there.

**Comment by iStefo** [comment]
Update: We both did not fully understand the behaviour and why value string splitting is important.

To be more specific: it's only important when using `multiple` enabled and with `optionValuePath` being set to true.

If that is the case, when a value update from select2 occurs, the ember component will receive a string like `item1,item2` and has to split at a given separator, which by default is `,`.
I made the `valueSeparator` option propagate to the internal select2 instance and removed `skipValueSeparator` again, because that is not an option ;)

Also, the ember component may now receive a string like `item1,item2` or `item1#item2` and will split correctly, if needed.

However, I disabled value string splitting when not using select2 in `multiple` mode (or with full object binding). That should solve this problem for most of the people. The rest can set the separator to a value that does not appear within their item ids, and therefore does not produce invalid items.

Since the options changed, I also refactored your tests a little to match my expectation of the component's behaviour, I hope thats fine with you. I will ship 1.3.0 very soon, maybe I will have a look into upgrading select2 to the most recent 3.x version, but only if that goes without problem.

Thanks for your support and taking part in this discussion!

**Pull request merged**
