### PR TITLE
Feature/tags

### PR DESCRIPTION
**Pull request by shunchu**
Merged steffenbrem's tags feature.

cr: @scottt2

### CODE REVIEW

**Comment by scottrblock** [comment]
Hi @shunchu, why was this closed/deleted? Happy to try to help if I can, though I'm still pretty new to ember. Looking into using this addon but need tagging support. Hoping @steffenbrem's PR is merged into master soon.

**Comment by shunchu** [comment]
@scottrblock, it was meant to merge into my own master for a project I'm working o, but I made a wrong PR. It's simply a slightly fixed up version of #92 with 2 differences:
* @scottt2 fixed an issue with ids
* It also includes changes found in my other pull request, #137

**Comment by scottrblock** [comment]
@shunchu great, thanks! Has your fork been working well for tagging so far?

**Comment by shunchu** [comment]
Yup. We just built a feature using it. It works great.

Here's how we're using it now:
* From our server, we eager-load all the tags we'd like to make available to our users
* When user enters strings that don't match one of the pre-loaded tags, `ember-select-2` will accept the strings as-is. And when user submits the form, we simply pass the entire tags payload to the server, and the server figures out which tags already exist and which ones need to be created and associated (we have a Rails app using this gem to deal with tagging: https://github.com/mbleigh/acts-as-taggable-on).

**Comment by shunchu** [comment]
Also, @steffenbrem, the original author who added the tagging support, added an example in the dummy app of the add-on. It's pretty self-explanatory once you looked at the dummy app's example.

**Comment by scottrblock** [comment]
Thanks @steffenbrem

**Pull request closed without merging**
