### PR TITLE
Ember Cli 1.13.8

### PR DESCRIPTION
**Pull request by blimmer**

### CODE REVIEW

**Comment by blimmer** [comment]
This runs locally with no problem. Anyone know what the
```Assertion after the final `assert.async` was resolved``` issue is?

**Comment by seven7seven** [comment]
Hi @blimmer, does this work on 1.13? Any idea why it hasn't been merged yet?

Trying to update my whole project all the way to 2.0, and I'm using select-2 quite intensively.

Thanks!

**Comment by blimmer** [comment]
the current release works on 1.13. I'm assuming this hasn't been merged because I don't know why these tests don't pass on Travis. Any help would be greatly appreciated.

**Comment by abobwhite** [comment]
It also probably hasn't been merged because this repo is slowly becoming un-maintained even though there is a very promising start. Pull requests and issues are going untouched by iStefo. Maybe he should open it up so others can approve PRs....?

**Comment by blimmer** [comment]
@iStefo what's your thought on @abobwhite 's comment. Is this repo something you want to transfer ownership of to someone else, or add new collabs?

**Comment by iStefo** [comment]
@blimmer @abobwhite you are right, and I addressed this issue to solve this problem https://github.com/iStefo/ember-select-2/issues/131

**Comment by blimmer** [comment]
this is old - closing

**Pull request closed without merging**
